name: Issue notifications

on:
  push:
    branches:
      - nadya73/issues-sync

jobs:
  mail:
    name: Send mail notification
    runs-on: trampoline
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.YTSAURUS_EMAIL}}
          password: ${{secrets.YTSAURUS_EMAIL_PASSWORD}}
          subject: Github Actions test
          to: ytsaurus-github-issues@yandex-team.ru
          from: GithubYTsaurus


